def test_imports():
    import xas
    import xas.analysis
    import xas.aux_qt_objects
    import xas.bin
    import xas.db_io
    import xas.energy_calibration
    import xas.factor_analysis
    import xas.file_io
    import xas.fitting
    import xas.ft_analysis
    import xas.handlers
    import xas.image_analysis
    import xas.interpolate
    import xas.math
    import xas.merge_scans
    import xas.metadata
    import xas.outliers
    import xas.pid
    import xas.process
    import xas.process_ioc
    import xas.scan_diagnostics
    import xas.scattering
    import xas.spectrometer
    import xas.tiled_io
    import xas.trajectory
    import xas.vonhamos
    import xas.xas_logger
    import xas.xasproject
    import xas.xdash_math
    import xas.xes_calibration
    import xas.xray
